services:

  db:
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ~/repos/nQueens/db:/var/lib/mysql
        #- ~/repos/nQueens/db/init.sql:/docker-entrypoint-initdb.d/init.sq
    networks:
      queensnetwork:
        ipv4_address: 172.20.0.10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ~/repos/nQueens:/queens   # Modify accordingly
    user: vscode
    depends_on:
      - db
    networks:
      queensnetwork:
        ipv4_address: 172.20.0.11

    #grafana:
    #  image: grafana/grafana-enterprise:8.2.0
    #  ports:
    #    - "3000:3000"

networks:
  queensnetwork:
    ipam:
      config:
        - subnet: 172.20.0.1/16
